In [6]:
x=0
if (x<0):
  print ("x is negative")
elif (x==0):
  print("x is 0")
else:
  print("x is positive")

x is 0


In [17]:
marks = int(input("Enter Student's marks: "))
#marks = int(input())
print(marks)
if marks>=90:
  print("Grade is S")
elif marks<90 and marks>=70:
  print("Grade is A")
elif marks<70 and marks>=50:
  print("Grade is B")
elif marks<50 and marks>=40:
  print("Grade is C")
else:
  print("Grade is E")

Enter Student's marks: 49
49
Grade is C


In [19]:
subjectmarks = [45,78,93,45,56]

In [20]:
for marks in subjectmarks:
  if marks>=90:
    print("Grade is S")
  elif marks<90 and marks>=70:
    print("Grade is A")
  elif marks<70 and marks>=50:
    print("Grade is B")
  elif marks<50 and marks>=40:
    print("Grade is C")
  else:
    print("Grade is E")

Grade is C
Grade is A
Grade is S
Grade is C
Grade is B


In [21]:
str1 = "Namasya"
for i in str1:
  print(i)

N
a
m
a
s
y
a


In [25]:
str2 = "NAmasya"
str2 = "aeiou"
count=0
for i in str2:
  if i.lower() in dict1:
    count = count + 1

print(count)

5


In [26]:
n=0
while(n<9):
  print(n)
  n = n+1

0
1
2
3
4
5
6
7
8


In [29]:
#Bubble sort
list1 = [6,8,4,7,89,45,67,3]
for i in range(len(list1)):
  for j in range(len(list1)-1):
    if list1[j] > list1[j+1]:
      list1[j], list1[j+1] = list1[j+1], list1[j]

print(list1)

[3, 4, 6, 7, 8, 45, 67, 89]


In [30]:
a = [6,8,4,7,89,45,67,3]
a.sort()

In [2]:
a = [6,8,4,7,89,45,67,3]
len(a)

8

In [17]:
import numpy as np
arr = np.random.randint(-9, 9, size=(6, 6))
print("\nArray with random integers:")
print(arr)
height = len(arr)
width = len(arr[0])
print(height)
print(width)
hourglass = []
for i in range(width-2):
  for j in range (height-2):
    sum = arr[i][j] + arr[i][j+1] + arr[i][j+2] + arr[i+1][j+1] + arr[i+2][j] + arr[i+2][j+1] + arr[i+2][j+2]
    #print(sum)
    hourglass.append(int(sum))
print(hourglass)
print(max(hourglass))


Array with random integers:
[[ 2 -6 -8 -6 -4  0]
 [ 8  6  5  6 -6 -5]
 [ 0 -8  1  5 -4 -6]
 [ 3 -3 -9  3  6 -9]
 [ 6  8 -4  1 -8 -5]
 [ 5  8 -1 -7 -8 -1]]
6
6
[-13, -17, -10, -21, 2, 9, 10, -9, 0, -6, -6, -11, 11, -13, -15, -24]
11
